# fly.toml app configuration file generated for server-lingering-breeze-8312 on 2025-05-26T01:09:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-lingering-breeze-8312'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
